
DROP SEQUENCE IF EXISTS SEQ_EXCHANGE
/
DROP SEQUENCE IF EXISTS SEQ_SECURITY_ENTITY
/
DROP SEQUENCE IF EXISTS SEQ_STOCK_DAY_TRADE
/
DROP SEQUENCE IF EXISTS SEQ_USER
/
CREATE SEQUENCE SEQ_EXCHANGE START WITH 1 INCREMENT BY 1 CACHE 100
/
CREATE SEQUENCE SEQ_SECURITY_ENTITY START WITH 1 INCREMENT BY 1 CACHE 100
/
CREATE SEQUENCE SEQ_STOCK_DAY_TRADE START WITH 1 INCREMENT BY 1 CACHE 100
/
CREATE SEQUENCE SEQ_USER START WITH 1 INCREMENT BY 1 CACHE 100