//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.03 at 06:59:54 PM CST 
//


package org.sjd.gordon.importing.profile.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.sjd.gordon.importing.profile.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.sjd.gordon.importing.profile.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DividendHistory }
     * 
     */
    public DividendHistory createDividendHistory() {
        return new DividendHistory();
    }

    /**
     * Create an instance of {@link StockSplits }
     * 
     */
    public StockSplits createStockSplits() {
        return new StockSplits();
    }

    /**
     * Create an instance of {@link TreasuryHeldStockHistory }
     * 
     */
    public TreasuryHeldStockHistory createTreasuryHeldStockHistory() {
        return new TreasuryHeldStockHistory();
    }

    /**
     * Create an instance of {@link DividendHistory.Dividend }
     * 
     */
    public DividendHistory.Dividend createDividendHistoryDividend() {
        return new DividendHistory.Dividend();
    }

    /**
     * Create an instance of {@link StockSplits.Split }
     * 
     */
    public StockSplits.Split createStockSplitsSplit() {
        return new StockSplits.Split();
    }

    /**
     * Create an instance of {@link StockEquity }
     * 
     */
    public StockEquity createStockEquity() {
        return new StockEquity();
    }

    /**
     * Create an instance of {@link StockEquities }
     * 
     */
    public StockEquities createStockEquities() {
        return new StockEquities();
    }

    /**
     * Create an instance of {@link TreasuryHeldStockHistory.TreasuryHeldStock }
     * 
     */
    public TreasuryHeldStockHistory.TreasuryHeldStock createTreasuryHeldStockHistoryTreasuryHeldStock() {
        return new TreasuryHeldStockHistory.TreasuryHeldStock();
    }

}
