//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.03 at 06:59:54 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.sjdelfab.org/gordon/stock_equity_profile", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.sjd.gordon.importing.profile.jaxb;
