//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.03 at 06:59:54 PM CST 
//


package org.sjd.gordon.importing.profile.jaxb;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="stock_equity" type="{http://www.sjdelfab.org/gordon/stock_equity_profile}stock_equity" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "stockEquity"
})
@XmlRootElement(name = "stock_equities")
public class StockEquities
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "stock_equity", required = true)
    protected List<StockEquity> stockEquity;

    /**
     * Gets the value of the stockEquity property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the stockEquity property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStockEquity().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StockEquity }
     * 
     * 
     */
    public List<StockEquity> getStockEquity() {
        if (stockEquity == null) {
            stockEquity = new ArrayList<StockEquity>();
        }
        return this.stockEquity;
    }

}
