//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.03 at 06:59:54 PM CST 
//


package org.sjd.gordon.importing.profile.jaxb;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for stock_equity complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="stock_equity">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="symbol" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="exchange" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="float_volume" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="industry_group" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="business_summary" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="stock_splits" type="{http://www.sjdelfab.org/gordon/stock_equity_profile}stock_splits"/>
 *         &lt;element name="treasury_held_stock_history" type="{http://www.sjdelfab.org/gordon/stock_equity_profile}treasury_held_stock_history"/>
 *         &lt;element name="dividend_history" type="{http://www.sjdelfab.org/gordon/stock_equity_profile}dividend_history"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "stock_equity", propOrder = {
    "symbol",
    "name",
    "exchange",
    "floatVolume",
    "industryGroup",
    "businessSummary",
    "stockSplits",
    "treasuryHeldStockHistory",
    "dividendHistory"
})
public class StockEquity
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    protected String symbol;
    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected String exchange;
    @XmlElement(name = "float_volume")
    protected int floatVolume;
    @XmlElement(name = "industry_group", required = true)
    protected String industryGroup;
    @XmlElement(name = "business_summary", required = true)
    protected String businessSummary;
    @XmlElement(name = "stock_splits", required = true)
    protected StockSplits stockSplits;
    @XmlElement(name = "treasury_held_stock_history", required = true)
    protected TreasuryHeldStockHistory treasuryHeldStockHistory;
    @XmlElement(name = "dividend_history", required = true)
    protected DividendHistory dividendHistory;

    /**
     * Gets the value of the symbol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSymbol() {
        return symbol;
    }

    /**
     * Sets the value of the symbol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSymbol(String value) {
        this.symbol = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the exchange property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExchange() {
        return exchange;
    }

    /**
     * Sets the value of the exchange property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExchange(String value) {
        this.exchange = value;
    }

    /**
     * Gets the value of the floatVolume property.
     * 
     */
    public int getFloatVolume() {
        return floatVolume;
    }

    /**
     * Sets the value of the floatVolume property.
     * 
     */
    public void setFloatVolume(int value) {
        this.floatVolume = value;
    }

    /**
     * Gets the value of the industryGroup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndustryGroup() {
        return industryGroup;
    }

    /**
     * Sets the value of the industryGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndustryGroup(String value) {
        this.industryGroup = value;
    }

    /**
     * Gets the value of the businessSummary property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBusinessSummary() {
        return businessSummary;
    }

    /**
     * Sets the value of the businessSummary property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBusinessSummary(String value) {
        this.businessSummary = value;
    }

    /**
     * Gets the value of the stockSplits property.
     * 
     * @return
     *     possible object is
     *     {@link StockSplits }
     *     
     */
    public StockSplits getStockSplits() {
        return stockSplits;
    }

    /**
     * Sets the value of the stockSplits property.
     * 
     * @param value
     *     allowed object is
     *     {@link StockSplits }
     *     
     */
    public void setStockSplits(StockSplits value) {
        this.stockSplits = value;
    }

    /**
     * Gets the value of the treasuryHeldStockHistory property.
     * 
     * @return
     *     possible object is
     *     {@link TreasuryHeldStockHistory }
     *     
     */
    public TreasuryHeldStockHistory getTreasuryHeldStockHistory() {
        return treasuryHeldStockHistory;
    }

    /**
     * Sets the value of the treasuryHeldStockHistory property.
     * 
     * @param value
     *     allowed object is
     *     {@link TreasuryHeldStockHistory }
     *     
     */
    public void setTreasuryHeldStockHistory(TreasuryHeldStockHistory value) {
        this.treasuryHeldStockHistory = value;
    }

    /**
     * Gets the value of the dividendHistory property.
     * 
     * @return
     *     possible object is
     *     {@link DividendHistory }
     *     
     */
    public DividendHistory getDividendHistory() {
        return dividendHistory;
    }

    /**
     * Sets the value of the dividendHistory property.
     * 
     * @param value
     *     allowed object is
     *     {@link DividendHistory }
     *     
     */
    public void setDividendHistory(DividendHistory value) {
        this.dividendHistory = value;
    }

}
